/* GENERATED by tools/extract_c14n.py from web/verify-receipt.html.
 * Do not edit: this is the pinned json-c14n v1 block, byte for byte.
 * tests/test_universal_checker.py fails if it drifts from the source. */
"use strict";
// C14N-START

function C14NError(message) {
  this.name = "C14NError";
  this.message = message;
}
C14NError.prototype = Object.create(Error.prototype);

// --- parser: JSON text -> a tagged tree that keeps int vs float distinct ---
// Node shapes: {t:'null'}, {t:'bool', v}, {t:'str', v}, {t:'num', kind, raw},
// {t:'arr', v: Array<node>}, {t:'obj', v: Map<string, node>} (Map so a
// duplicate key resolves the same way Python's json.loads does: last write
// wins, and lookups are by exact string).
function parseC14NValue(text) {
  let i = 0;
  const n = text.length;

  function fail(msg) { throw new C14NError(msg + " (at position " + i + ")"); }

  function skipWs() {
    while (i < n) {
      const c = text[i];
      if (c === " " || c === "\t" || c === "\n" || c === "\r") { i++; }
      else { break; }
    }
  }

  function parseValue() {
    skipWs();
    if (i >= n) { fail("unexpected end of input"); }
    const c = text[i];
    if (c === "{") { return parseObject(); }
    if (c === "[") { return parseArray(); }
    if (c === '"') { return { t: "str", v: parseString() }; }
    if (c === "-" || (c >= "0" && c <= "9")) { return parseNumber(); }
    if (text.startsWith("true", i)) { i += 4; return { t: "bool", v: true }; }
    if (text.startsWith("false", i)) { i += 5; return { t: "bool", v: false }; }
    if (text.startsWith("null", i)) { i += 4; return { t: "null", v: null }; }
    fail("unexpected token " + JSON.stringify(c));
  }

  function parseObject() {
    i++; // consume '{'
    const map = new Map();
    skipWs();
    if (text[i] === "}") { i++; return { t: "obj", v: map }; }
    for (;;) {
      skipWs();
      if (text[i] !== '"') { fail("expected a string key"); }
      const key = parseString();
      skipWs();
      if (text[i] !== ":") { fail('expected ":"'); }
      i++;
      const val = parseValue();
      map.set(key, val); // duplicate key: last one wins, same as json.loads
      skipWs();
      if (text[i] === ",") { i++; continue; }
      if (text[i] === "}") { i++; break; }
      fail('expected "," or "}"');
    }
    return { t: "obj", v: map };
  }

  function parseArray() {
    i++; // consume '['
    const arr = [];
    skipWs();
    if (text[i] === "]") { i++; return { t: "arr", v: arr }; }
    for (;;) {
      arr.push(parseValue());
      skipWs();
      if (text[i] === ",") { i++; continue; }
      if (text[i] === "]") { i++; break; }
      fail('expected "," or "]"');
    }
    return { t: "arr", v: arr };
  }

  function parseString() {
    i++; // consume opening quote
    let out = "";
    for (;;) {
      if (i >= n) { fail("unterminated string"); }
      const c = text[i];
      if (c === '"') { i++; break; }
      if (c === "\\") {
        i++;
        const e = text[i];
        if (e === '"') { out += '"'; i++; }
        else if (e === "\\") { out += "\\"; i++; }
        else if (e === "/") { out += "/"; i++; }
        else if (e === "b") { out += "\b"; i++; }
        else if (e === "f") { out += "\f"; i++; }
        else if (e === "n") { out += "\n"; i++; }
        else if (e === "r") { out += "\r"; i++; }
        else if (e === "t") { out += "\t"; i++; }
        else if (e === "u") {
          const hex = text.slice(i + 1, i + 5);
          if (!/^[0-9a-fA-F]{4}$/.test(hex)) { fail("bad \\u escape"); }
          out += String.fromCharCode(parseInt(hex, 16));
          i += 5;
        } else {
          fail("bad escape \\" + e);
        }
      } else if (c.charCodeAt(0) < 0x20) {
        fail("unescaped control character in string literal");
      } else {
        out += c;
        i++;
      }
    }
    return out;
  }

  function isDigit(c) { return c >= "0" && c <= "9"; }

  function parseNumber() {
    const start = i;
    if (text[i] === "-") { i++; }
    if (text[i] === "0") {
      i++;
    } else if (isDigit(text[i])) {
      while (i < n && isDigit(text[i])) { i++; }
    } else {
      fail("invalid number");
    }
    let isFloat = false;
    if (text[i] === ".") {
      isFloat = true;
      i++;
      if (!isDigit(text[i])) { fail("invalid number: digit required after '.'"); }
      while (i < n && isDigit(text[i])) { i++; }
    }
    if (text[i] === "e" || text[i] === "E") {
      isFloat = true;
      i++;
      if (text[i] === "+" || text[i] === "-") { i++; }
      if (!isDigit(text[i])) { fail("invalid number: digit required in exponent"); }
      while (i < n && isDigit(text[i])) { i++; }
    }
    return { t: "num", kind: isFloat ? "float" : "int", raw: text.slice(start, i) };
  }

  const result = parseValue();
  skipWs();
  if (i !== n) { fail("trailing data after the JSON value"); }
  return result;
}

// --- key ordering: Unicode CODE POINT order, matching Python's `str` `<` ---
// (Deliberately NOT UTF-16 code-unit order / RFC 8785 JCS order -- those
// diverge from this recipe for keys containing astral-plane characters. See
// arcaeon_ledger/artefact.py's own note on this exact divergence.)
function codepoints(s) {
  return Array.from(s).map(function (ch) { return ch.codePointAt(0); });
}
function compareByCodepoint(a, b) {
  const A = codepoints(a), B = codepoints(b);
  const len = Math.min(A.length, B.length);
  for (let k = 0; k < len; k++) {
    if (A[k] !== B[k]) { return A[k] - B[k]; }
  }
  return A.length - B.length;
}

// --- string encoding: escape only what Python's ensure_ascii=False escapes ---
function encodeC14NString(s) {
  let out = '"';
  for (let k = 0; k < s.length; k++) {
    const c = s[k];
    const code = s.charCodeAt(k);
    if (c === '"') { out += '\\"'; }
    else if (c === "\\") { out += "\\\\"; }
    else if (c === "\n") { out += "\\n"; }
    else if (c === "\r") { out += "\\r"; }
    else if (c === "\t") { out += "\\t"; }
    else if (code === 0x08) { out += "\\b"; }
    else if (code === 0x0c) { out += "\\f"; }
    else if (code < 0x20) { out += "\\u" + code.toString(16).padStart(4, "0"); }
    else { out += c; }
  }
  return out + '"';
}

// --- integers: reproduce the literal digit text exactly (arbitrary precision) ---
function formatC14NInt(raw) {
  let s = raw;
  let neg = false;
  if (s[0] === "-") { neg = true; s = s.slice(1); }
  if (/^0+$/.test(s)) { return "0"; } // Python: int("-0") == 0 -> "0"
  return (neg ? "-" : "") + s;
}

// --- floats: reformat to Python's repr() shape from JS's own shortest,
// round-trip-correct decimal digits (via toExponential()). Both languages
// implement the same "shortest string that round-trips to this double"
// contract; only the LAYOUT (fixed vs scientific, exponent padding, sign)
// differs, and that layout is reproduced here explicitly. ---
function formatC14NFloat(raw) {
  const num = Number(raw);
  if (!isFinite(num)) {
    throw new C14NError("float overflows to Infinity, cannot canonicalize (Python's " +
      "own encoder refuses this too, via allow_nan=False): " + raw);
  }
  if (num === 0) {
    // Number(raw) with raw "-0.0" or "-0" written as a float literal yields
    // JS's signed zero; toExponential() on -0 drops the sign, so it must be
    // recovered explicitly.
    return (Object.is(num, -0) ? "-0.0" : "0.0");
  }
  const neg = num < 0;
  const abs = Math.abs(num);
  const exp = abs.toExponential(); // shortest round-trip digits, e.g. "1.5e+300"
  const m = /^(\d)(?:\.(\d+))?e([+-]\d+)$/.exec(exp);
  if (!m) { throw new C14NError("could not parse exponential form: " + exp); }
  const digits = m[1] + (m[2] || "");
  const exponent = parseInt(m[3], 10); // value == digits[0].digits[1:] * 10^exponent
  const decpt = exponent + 1;          // Python dtoa convention: value == 0.<digits> * 10^decpt
  const useExp = (decpt <= -4) || (decpt > 16); // CPython's float_repr_style threshold
  let body;
  if (useExp) {
    const mantissa = digits.length > 1 ? (digits[0] + "." + digits.slice(1)) : digits[0];
    const e = decpt - 1;
    const esign = e < 0 ? "-" : "+";
    const estr = String(Math.abs(e)).padStart(2, "0");
    body = mantissa + "e" + esign + estr;
  } else if (decpt <= 0) {
    body = "0." + "0".repeat(-decpt) + digits;
  } else if (decpt >= digits.length) {
    body = digits + "0".repeat(decpt - digits.length) + ".0";
  } else {
    body = digits.slice(0, decpt) + "." + digits.slice(decpt);
  }
  return (neg ? "-" : "") + body;
}

function canonicalizeC14N(node) {
  switch (node.t) {
    case "null": return "null";
    case "bool": return node.v ? "true" : "false";
    case "str": return encodeC14NString(node.v);
    case "num": return node.kind === "int" ? formatC14NInt(node.raw) : formatC14NFloat(node.raw);
    case "arr": return "[" + node.v.map(canonicalizeC14N).join(",") + "]";
    case "obj": {
      const keys = Array.from(node.v.keys()).sort(compareByCodepoint);
      return "{" + keys.map(function (k) {
        return encodeC14NString(k) + ":" + canonicalizeC14N(node.v.get(k));
      }).join(",") + "}";
    }
    default: throw new C14NError("unknown node type " + node.t);
  }
}

// Entry point used by both this page and the parity test: JSON text in,
// canonical json-c14n v1 string out.
function c14nCanonicalize(text) {
  return canonicalizeC14N(parseC14NValue(text));
}

// C14N-END
