/* GENERATED by tools/extract_c14n.py from web/verify-receipt.html.
 * Do not edit: this is the pinned cross-check block (the witness block and
 * the attestation signature against the receipt), byte for byte.
 * tests/test_universal_checker.py fails if it drifts from the source. */
"use strict";
// CROSSCHECK-START
/* ----------------------------------------------------------------------------
 * The cross-checks, one source for two pages (2026-09-22).
 *
 * Everything between CROSSCHECK-START and CROSSCHECK-END is also what
 * verify-any.html runs on an Arcaeon receipt: tools/extract_c14n.py writes it,
 * byte for byte, to web/universal/crosscheck_pinned.js, and
 * tests/test_universal_checker.py fails if the two ever differ. So the two
 * pages cannot disagree about a witness block or an attestation signature
 * without that test going red. Pure: no DOM. Needs the C14N block above and a
 * sha256Hex(bytes) -> Promise<hex> from the page that loads it.
 * --------------------------------------------------------------------------*/

function getField(objNode, key) {
  if (!objNode || objNode.t !== "obj" || !objNode.v.has(key)) { return null; }
  return objNode.v.get(key);
}
function asString(node) { return node && node.t === "str" ? node.v : null; }

function prettyNode(node, ind) {
  const pad = "  ".repeat(ind);
  const pad2 = "  ".repeat(ind + 1);
  switch (node.t) {
    case "null": return "null";
    case "bool": return node.v ? "true" : "false";
    case "num": return node.raw; // display raw literal text: never lossy, even for huge ints
    case "str": return JSON.stringify(node.v);
    case "arr":
      if (node.v.length === 0) { return "[]"; }
      return "[\n" + node.v.map(function (x) { return pad2 + prettyNode(x, ind + 1); }).join(",\n") + "\n" + pad + "]";
    case "obj": {
      const keys = Array.from(node.v.keys());
      if (keys.length === 0) { return "{}"; }
      return "{\n" + keys.map(function (k) {
        return pad2 + JSON.stringify(k) + ": " + prettyNode(node.v.get(k), ind + 1);
      }).join(",\n") + "\n" + pad + "}";
    }
    default: return String(node);
  }
}

/* ============================================================================
 * Attachments outside the body digest (2026-09-22).
 *
 * `ledger`, `witness`, `anchor` and `attestation_signature` are the issuer's
 * statements about the body, attached after the digest exists. Editing any of
 * them leaves the body digest PASS untouched, so this page must never print
 * them beside that PASS as if they had been checked. The same rules as the
 * Python verifier (arcaeon_receipt/core.py, _check_witness and
 * _check_attestation_signature):
 *   claimed        the issuer says so; nothing here can check it offline
 *   could not look checkable in principle, but the receipt carries no key
 *   inconsistent / mismatch
 *                  the attachment contradicts the receipt itself: determined,
 *                  so the batch verdict is FAIL
 * ==========================================================================*/

// Python's json.dumps(obj, sort_keys=True, ensure_ascii=False) with its
// DEFAULT separators (", " and ": "), which is the recipe arcaeon_ledger's
// WitnessStore uses for a pin's `self` digest. Same string/number rules as
// json-c14n v1, so it reuses those helpers and leaves the C14N block alone.
function pyDefaultDumps(node) {
  switch (node.t) {
    case "null": return "null";
    case "bool": return node.v ? "true" : "false";
    case "str": return encodeC14NString(node.v);
    case "num": return node.kind === "int" ? formatC14NInt(node.raw) : formatC14NFloat(node.raw);
    case "arr": return "[" + node.v.map(pyDefaultDumps).join(", ") + "]";
    case "obj": {
      const keys = Array.from(node.v.keys()).sort(compareByCodepoint);
      return "{" + keys.map(function (k) {
        return encodeC14NString(k) + ": " + pyDefaultDumps(node.v.get(k));
      }).join(", ") + "}";
    }
    default: throw new C14NError("unknown node type " + node.t);
  }
}

function sameValue(a, b) {
  if (a.t === "num" && b.t === "num") {
    if (a.raw === b.raw) { return true; }
    try { return Number(a.raw) === Number(b.raw); } catch (e) { return false; }
  }
  try { return canonicalizeC14N(a) === canonicalizeC14N(b); } catch (e) { return false; }
}

async function checkWitness(receiptRoot) {
  const witness = getField(receiptRoot, "witness");
  if (witness === null) { return { verdict: "absent", problems: [] }; }
  if (witness.t !== "obj") { return { verdict: "inconsistent", problems: ["the witness block is not an object"] }; }
  const hasAny = ["kind", "pin", "rows", "chain"].some(function (k) { return witness.v.has(k); });
  if (asString(getField(witness, "status")) === "skipped" && !hasAny) {
    return { verdict: "absent", problems: [] };
  }
  const ledgerNode = getField(receiptRoot, "ledger");
  const ledger = ledgerNode && ledgerNode.t === "obj" ? ledgerNode : null;
  const problems = [];
  ["rows", "chain", "namespace"].forEach(function (k) {
    const w = getField(witness, k), l = ledger ? getField(ledger, k) : null;
    if (w !== null && l !== null && !sameValue(w, l)) {
      problems.push("witness." + k + " (" + prettyNode(w, 0) + ") disagrees with ledger." + k +
        " (" + prettyNode(l, 0) + ")");
    }
  });
  let pinSelf = "not_present";
  const pin = getField(witness, "pin");
  if (pin !== null) {
    if (pin.t !== "obj") {
      problems.push("witness.pin is not an object");
    } else {
      ["rows", "chain", "namespace"].forEach(function (k) {
        const pv = getField(pin, k), wv = getField(witness, k);
        if (pv !== null && wv !== null && !sameValue(pv, wv)) {
          problems.push("witness.pin." + k + " (" + prettyNode(pv, 0) + ") disagrees with witness." + k +
            " (" + prettyNode(wv, 0) + ")");
        }
      });
      if (pin.v.has("self") && pin.v.has("prev")) {
        const m = new Map();
        pin.v.forEach(function (v, k) { if (k !== "prev" && k !== "self") { m.set(k, v); } });
        let text = null;
        try { text = pyDefaultDumps({ t: "obj", v: m }); } catch (e) { text = null; }
        // A lone surrogate is legal JSON, and Python hashes it with
        // surrogatepass; TextEncoder cannot reproduce those bytes, so say
        // "not recomputed here" rather than accuse the pin.
        if (text === null || /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:^|[^\uD800-\uDBFF])[\uDC00-\uDFFF]/.test(text)) {
          pinSelf = "not_recomputed";
        } else {
          const hex = await sha256Hex(new TextEncoder().encode(text));
          if (hex.slice(0, 32) === asString(getField(pin, "self"))) {
            pinSelf = "checked";
          } else {
            pinSelf = "mismatch";
            problems.push("witness.pin.self does not recompute: the pin was edited after it was recorded");
          }
        }
      }
    }
  }
  return { verdict: problems.length ? "inconsistent" : "claimed", problems: problems, pinSelf: pinSelf };
}

function checkAttestationSignature(receiptRoot, claimedDigest) {
  const sig = getField(receiptRoot, "attestation_signature");
  if (sig === null) { return { verdict: "absent", problems: [] }; }
  if (sig.t !== "obj") { return { verdict: "mismatch", problems: ["attestation_signature is not an object"] }; }
  const problems = [];
  const over = getField(sig, "signed_over");
  if (over !== null && asString(over) !== "body_digest") {
    problems.push("signed_over is " + prettyNode(over, 0) + ", not \"body_digest\"");
  }
  const bd = getField(sig, "body_digest");
  if (bd === null || asString(bd) === null || asString(bd) !== claimedDigest) {
    problems.push("the signature says it was made over a different body digest (" +
      (bd === null ? "none" : prettyNode(bd, 0)) + ") than this receipt carries");
  }
  return { verdict: problems.length ? "mismatch" : "could_not_look", problems: problems };
}
// CROSSCHECK-END
