"""Bulk export: one portable file a coordinator can hand to a stranger.

VENDOR_PACKAGE_SPEC 2.5, the half that was still unbuilt. The other half
landed in 4033305: bulk verification answers over a class in one pass. This
is the archive itself, and what it is for is the sentence in 2.5 -- the
class "in a form they own and can hand to anybody, including us going
away." An export that only works while we are still here is not an export.

WHAT GOES IN, AND WHY THAT SHAPE.

    MANIFEST.json        what this archive is, what is in it, each file's
                         sha256, the verdict of every receipt, and the scope
                         block verbatim
    README.txt           how a human with no tools checks it
    roster_report.csv    the coordinator's own page (roster_report.py, not
                         reimplemented here)
    cohort/              the export, byte for byte: every receipt, every
                         exhibit, the ledger files those receipts name, and
                         the witness sidecars beside them

Everything under `cohort/` is a byte-identical copy of what the vendor
already holds. Everything at the root is generated by this command. The
split is so a reader can tell at a glance which files we made and which
files we only moved.

`cohort/` is FLAT, and that is load-bearing rather than tidy: a receipt
finds its ledger by looking for that filename beside itself
(`verify_batch.resolve_ledger`, basename only), which is the shape an
export directory already has. Sorting receipts into `receipts/` and ledgers
into `ledger/` would make every extracted receipt come back `undetermined`
for want of a ledger nobody could find. The archive extracts into the shape
the verifier already knows.

THE WHOLE LEDGER FILE, NOT THE ROWS. A hash chain cannot be subset. The
verifier walks the file from its first row (`arcaeon_ledger.verify_file`),
so a ledger holding only the rows this class references would fail its own
chain check and every receipt in the archive would read `FAIL` for a reason
that is an artifact of the packing. The referenced rows arrive inside the
file that makes them checkable.

NOTHING IS MUTATED ON THE WAY IN. Receipts are copied as bytes and their
sha256 is recomputed from the archive after it is written, before this
function returns. A re-serialized receipt -- same values, different key
order or indentation -- verifies fine and is still the wrong thing to ship:
the archive is evidence, and evidence that was rewritten in transit invites
the one question the whole product exists to close.

A FAIL IS PACKED. A receipt that does not verify goes in with its verdict
on the manifest, next to the ones that do. Dropping it would make the
archive a curated exhibit instead of a record, and the coordinator running
this is looking for exactly that receipt. The exit code says a FAIL is in
there (2), or that something could not be determined (4); the archive is
written either way.

NO AGGREGATE ABOUT SCORES. Same rule as the roster report, for the same
reason quoted there: the scope block denies "the score is correct", and an
average, a rate, or an ordering asserts its opposite by arithmetic. The
counts in this manifest are VERDICT counts -- how many receipts verify --
and never a statistic about what the grading engine returned. A grep over a
real archive holds it.

THE CAP PAGES, IT DOES NOT REFUSE. Verification here runs through
`roster_report.build_report`, which pages in runs of the published 20 and
prints its own pass structure. `roster_report.py`'s docstring carries the
argument and the honest counter-argument; this module takes the same
position for the same reason, and would move with it if the cap is ever
re-read as a commercial limit rather than the anti-truncation rule it is
written as.

DETERMINISTIC. The same cohort archived twice produces byte-identical zip
files apart from `generated_at`: entries are written in a fixed order, with
a fixed timestamp (zip files otherwise stamp the wall clock into every
entry header) and a fixed create_system, and the one clock reading is taken
once and shared by the manifest and the roster report. Two archives of the
same class that differ in bytes make a reader ask which one is the real
one, and there is no good answer to that question.
"""
from __future__ import annotations

import hashlib
import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from . import roster_report, verify_batch
from .verify_batch import FAIL, OK, UNDETERMINED

ARCHIVE_VERSION = "arcaeon-receipt-archive/1"

MANIFEST_NAME = "MANIFEST.json"
README_NAME = "README.txt"
ROSTER_NAME = "roster_report.csv"
COHORT_DIR = "cohort"

#: Every zip entry is stamped with this instead of the wall clock. 1980-01-01
#: is the zero of the DOS timestamp the format stores, so it is the one value
#: that survives a round trip through every unzip tool unchanged.
FIXED_ZIP_DATE = (1980, 1, 1, 0, 0, 0)

#: Written into every entry header so an archive built on Windows and one
#: built on Linux from the same cohort are the same bytes. 3 is Unix.
ZIP_CREATE_SYSTEM = 3

#: Where a stranger goes to check this without installing anything. Until
#: 2026-09-23 this named `web/verify-receipt.html` in a GitHub repo
#: (github.com/Arcaeon-io/arcaeon-receipt) that does not exist publicly: the
#: URL returned 404 on 2026-09-23, so every archive's README sent its reader
#: to a dead link. The hosted page is now live: https://arcaeon.io/verify-receipt
#: returned 200 on 2026-09-23 and its bytes equal the site's source copy, which
#: passes the parity test (verbatim `web/verify-receipt.html` plus two marked
#: chrome blocks, no external `src`/`href`, no fetch). It runs entirely in the
#: reader's browser and calls nothing, so a saved copy is the same verifier.
VERIFIER_PAGE_URL = "https://arcaeon.io/verify-receipt"

EXHIBIT_SUFFIX = ".exhibit.txt"
RECEIPT_SUFFIX = ".receipt.json"
WITNESS_SUFFIX = ".witness.jsonl"


class ArchiveIntegrityError(RuntimeError):
    """A file did not come out of the finished archive as the bytes that went
    in. Raised after writing and before returning, so a caller never gets a
    success line over an archive whose contents moved."""


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# --------------------------------------------------------------------------
# gathering the files
# --------------------------------------------------------------------------

def _ledger_files(receipt_paths: List[Path],
                  explicit: Optional[str | Path]) -> List[Path]:
    """Every ledger a receipt in this batch names, plus its witness sidecar.

    Resolution is `verify_batch.resolve_ledger`'s, not a second rule written
    here: the archive must bundle the file the verifier will go looking for,
    and the only way to be sure of that is to ask the verifier.
    """
    out: List[Path] = []
    seen = set()
    for p in receipt_paths:
        try:
            rc = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue          # already an `undetermined` row; not a crash here
        if not isinstance(rc, dict):
            continue
        led, _ = verify_batch.resolve_ledger(rc, p, explicit)
        if led is None:
            continue
        for cand in (led, Path(str(led) + WITNESS_SUFFIX)):
            key = str(cand.resolve()).lower()
            if cand.exists() and cand.is_file() and key not in seen:
                seen.add(key)
                out.append(cand)
    return out


def _exhibit_of(receipt_path: Path) -> Optional[Path]:
    """The human-readable half of the pair, if the vendor kept it.

    `<name>.receipt.json` -> `<name>.exhibit.txt`, the pair `ballot` and
    `cite` write. The exhibit is what a hiring manager actually reads, and
    2.5 promises it inside the export; it is optional here because an export
    directory that holds only receipts is still a valid export.
    """
    name = receipt_path.name
    if not name.endswith(RECEIPT_SUFFIX):
        return None
    cand = receipt_path.with_name(name[:-len(RECEIPT_SUFFIX)] + EXHIBIT_SUFFIX)
    return cand if cand.exists() else None


def gather(target: str | Path, *, ledger_path: Optional[str | Path] = None) -> List[tuple]:
    """[(archive path, source path)] for everything copied in verbatim.

    Ordered: receipts first (the thing being proved), then exhibits, then
    ledgers and their sidecars, each group sorted by archive path. Fixed
    order is half of the determinism guarantee; the other half is the fixed
    timestamp at write time.
    """
    receipts, from_target = roster_report.resolve_target(target)
    if not receipts:
        raise verify_batch.NoReceiptsFound(
            f"no receipts under {target}: an archive is built from a cohort "
            f"directory of {verify_batch.RECEIPT_GLOB} files, or from the "
            "class ledger sitting beside them"
        )
    led = ledger_path if ledger_path is not None else from_target

    pairs: List[tuple] = []
    for p in receipts:
        pairs.append((f"{COHORT_DIR}/{p.name}", p))
    exhibits = [_exhibit_of(p) for p in receipts]
    for ex in sorted((e for e in exhibits if e is not None), key=lambda p: p.name):
        pairs.append((f"{COHORT_DIR}/{ex.name}", ex))
    for lp in sorted(_ledger_files(receipts, led), key=lambda p: p.name):
        pairs.append((f"{COHORT_DIR}/{lp.name}", lp))

    by_path = {}
    for arc, src in pairs:           # a name collision would silently drop a file
        if arc in by_path and by_path[arc].resolve() != src.resolve():
            raise ValueError(
                f"two different files would both be archived as {arc}: "
                f"{by_path[arc]} and {src}"
            )
        by_path[arc] = src
    return [(arc, by_path[arc]) for arc in sorted(by_path)]


# --------------------------------------------------------------------------
# the manifest
# --------------------------------------------------------------------------

def _receipt_rows(report: dict) -> List[dict]:
    """One entry per receipt, verdict included, FAIL and undetermined with
    the rest. The row order is the report's, so the manifest and the CSV
    cannot disagree about what was in the class."""
    return [{"file": f"{COHORT_DIR}/{r['file']}",
             "receipt_id": r["receipt_id"],
             "trainee": r["trainee"],
             "verdict": r["verdict"],
             "ledger": r["ledger"],
             "anchor": r["anchor"],
             "reason": r["reason"]} for r in report["rows"]]


def build_manifest(report: dict, files: List[dict], *, source: str,
                   generated_at: str) -> dict:
    """What this archive is, what is in it, and what every file hashes to.

    `scope_proves` / `scope_does_not_prove` are the report header's own
    strings, which are read verbatim out of the receipts by
    `roster_report._scope_text`. Copied rather than restated so the manifest
    and the roster report cannot drift into two versions of the claim.
    """
    h = report["header"]
    counts = {"receipts": int(h["receipts_counted"]), OK: int(h["verified"]),
              FAIL: int(h["failed"]), UNDETERMINED: int(h["undetermined"])}
    return {
        "archive_version": ARCHIVE_VERSION,
        "generated_at": generated_at,
        "issuer": h["issuer"],
        "cohort": h["cohort"],
        "source": source,
        "scope_proves": h["scope_proves"],
        "scope_does_not_prove": h["scope_does_not_prove"],
        "verdict_counts": counts,
        "verification_passes": h["verification_passes"],
        "receipts": _receipt_rows(report),
        "digest_algorithm": "sha256 over the file's bytes, lowercase hex",
        "manifest_covers": ("every file in this archive except "
                            f"{MANIFEST_NAME} itself"),
        "files": files,
    }


def manifest_json(manifest: dict) -> str:
    return json.dumps(manifest, indent=1, ensure_ascii=False) + "\n"


def exit_code(manifest: dict) -> int:
    """0 / 2 / 4, the same three meanings as `verify --batch` and the roster
    report. The archive is written at every one of them: an export that
    refused to build because a receipt failed would hide the receipt the
    coordinator is looking for."""
    c = manifest["verdict_counts"]
    if c[FAIL]:
        return 2
    if c[UNDETERMINED]:
        return 4
    return 0


# --------------------------------------------------------------------------
# the README a stranger opens
# --------------------------------------------------------------------------

def readme_text(manifest: dict) -> str:
    """Plain ASCII, written for somebody with no tools and no account.

    Two routes, both free, neither needing anything from us: a page that
    runs in their own browser, and a command. Nothing here states or implies
    anything about how the class did -- the scope block is quoted, and the
    counts named are verdict counts.
    """
    c = manifest["verdict_counts"]
    lines = [
        "WHAT THIS FILE IS",
        "",
        "A sealed record of one training cohort: every graded ballot receipt",
        "the academy issued, the plain-text exhibit that goes with each one,",
        "and the hash-chained ledger those receipts were written into.",
        "",
        f"Issuer:  {manifest['issuer']}",
        f"Cohort:  {manifest['cohort']}",
        f"Built:   {manifest['generated_at']} (UTC)",
        f"Holds:   {c['receipts']} receipts",
        "",
        "WHAT A RECEIPT CLAIMS, IN ITS OWN WORDS",
        "",
        f"  Proves:           {manifest['scope_proves']}",
        f"  Does NOT prove:   {manifest['scope_does_not_prove']}",
        "",
        "Read that second line twice. This archive shows that the scores in",
        "it have not been altered since they were issued. It says nothing",
        "about whether any score is the right score. That is the grading",
        "vendor's question and this archive does not touch it.",
        "",
        "HOW TO CHECK IT YOURSELF",
        "",
        "Verification is free, needs no account, and needs nothing from the",
        "people who issued this. Two ways, either one is enough:",
        "",
        "1. In your browser, nothing installed.",
        "   Get the verifier page:",
        f"     {VERIFIER_PAGE_URL}",
        "   Save it and open it. It runs entirely inside your browser and",
        "   sends nothing anywhere, so it works with the network off. Drag",
        f"   the receipt files from {COHORT_DIR}/ onto the page. It recomputes",
        "   each digest and tells you, one line per receipt, whether the",
        "   document still matches what was sealed.",
        "",
        "2. At a command line.",
        "     pip install arcaeon-receipt",
        f"     arcaeon-receipt verify --batch {COHORT_DIR}/",
        "   The ledger sits beside the receipts in that folder, so the",
        "   sequence claim on each receipt is checked too. Exit code 0 means",
        "   every receipt VERIFIED, 2 means at least one is BROKEN, 4 means",
        "   nothing is BROKEN but the check COULD NOT LOOK at one or more.",
        "",
        "CHECKING THAT NOTHING IN HERE WAS SWAPPED",
        "",
        f"{MANIFEST_NAME} lists every other file in this archive with the",
        "sha256 of its bytes. On macOS or Linux:",
        "",
        f"     shasum -a 256 {COHORT_DIR}/<filename>",
        "",
        "On Windows PowerShell:",
        "",
        f"     Get-FileHash {COHORT_DIR}\\<filename> -Algorithm SHA256",
        "",
        "Compare what comes back to the entry in the manifest. A receipt",
        "that was edited after this archive was built will not match, and it",
        "will also fail the digest check in step 1 or 2 above, which is the",
        "check that matters: the manifest proves the archive is intact, and",
        "the receipt proves itself.",
        "",
        "WHAT IS IN THE FOLDERS",
        "",
        f"  {MANIFEST_NAME.ljust(20)}this archive's contents and their digests",
        f"  {ROSTER_NAME.ljust(20)}one row per trainee, for the coordinator",
        f"  {(COHORT_DIR + '/').ljust(20)}the export itself, copied here unchanged",
        "",
        "Every file under that folder is a byte-for-byte copy of what the",
        "academy holds. Nothing was reformatted on the way in; a receipt that",
        "was rewritten in transit would still verify, and would still be the",
        "wrong thing to hand you.",
        "",
        "A RECEIPT THAT DOES NOT VERIFY IS STILL IN HERE",
        "",
        f"When this archive was built, of its {c['receipts']} receipts: "
        f"{c[OK]} VERIFIED,",
        f"{c[FAIL]} BROKEN, and {c[UNDETERMINED]} COULD NOT LOOK.",
        "",
        "Any receipt that failed is in here with the others and named on the",
        "manifest with its verdict. An export that quietly dropped them would",
        "be a brochure, not a record, and the receipt somebody is looking for",
        "is usually the one that stopped verifying.",
        "",
        "The verdicts above are about documents, not about people. They say",
        "which files still match what was sealed. They are not a statement",
        "about how anyone did.",
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# building
# --------------------------------------------------------------------------

def _write_zip(out: Path, entries: List[tuple]) -> None:
    """[(archive path, bytes)] -> one zip, deterministic bytes.

    Fixed date, fixed create_system, fixed order, deflate at the library
    default. Nothing here reads the clock or the filesystem's metadata.
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for arcname, data in entries:
            info = zipfile.ZipInfo(arcname, date_time=FIXED_ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.create_system = ZIP_CREATE_SYSTEM
            info.external_attr = 0o644 << 16
            z.writestr(info, data)


def _audit(out: Path, manifest: dict, sources: dict) -> None:
    """Read the finished archive back and prove every file survived the trip.

    Two comparisons, not one: each entry against the digest on the manifest,
    and each copied-in file against the bytes still on disk. The first catches
    a packing bug, the second catches a manifest that agrees with a file this
    module already altered.
    """
    with zipfile.ZipFile(out) as z:
        names = set(z.namelist())
        expected = {f["path"] for f in manifest["files"]} | {MANIFEST_NAME}
        if names != expected:
            missing, extra = sorted(expected - names), sorted(names - expected)
            raise ArchiveIntegrityError(
                f"archive contents do not match the manifest: missing "
                f"{missing}, unexpected {extra}")
        for entry in manifest["files"]:
            got = _sha256(z.read(entry["path"]))
            if got != entry["sha256"]:
                raise ArchiveIntegrityError(
                    f"{entry['path']} came out of the archive as {got}, the "
                    f"manifest says {entry['sha256']}")
            src = sources.get(entry["path"])
            if src is not None and _sha256(src.read_bytes()) != got:
                raise ArchiveIntegrityError(
                    f"{entry['path']} is not byte-identical to its source "
                    f"{src}: a receipt was altered on the way into the archive")


def build_archive(target: str | Path, out: str | Path, *,
                  ledger_path: Optional[str | Path] = None, ots: bool = False,
                  generated_at: Optional[str] = None) -> dict:
    """Build the archive at `out`, return its manifest.

    One clock reading, taken here and handed to both the roster report and
    the manifest, so the two documents in the archive agree about when it was
    made and so two runs differ in exactly one value.
    """
    stamp = generated_at or _now()
    pairs = gather(target, ledger_path=ledger_path)
    report = roster_report.build_report(target, ledger_path=ledger_path, ots=ots,
                                        generated_at=stamp)

    packed = {arc: src.read_bytes() for arc, src in pairs}
    sources = {arc: src for arc, src in pairs}

    # the report's rows and the copied receipts must be the same set of files,
    # or the manifest is describing a class the archive does not hold
    reported = {f"{COHORT_DIR}/{r['file']}" for r in report["rows"]}
    if not reported <= set(packed):
        raise ArchiveIntegrityError(
            "the roster report covers receipts the archive does not hold: "
            f"{sorted(reported - set(packed))}")

    roster_csv = roster_report.to_csv(report).encode("utf-8")
    body = [(ROSTER_NAME, roster_csv)] + [(arc, packed[arc]) for arc, _ in pairs]

    files = [{"path": arc, "bytes": len(data), "sha256": _sha256(data)}
             for arc, data in body]
    manifest = build_manifest(report, files, source=str(target), generated_at=stamp)

    # The README is written FROM the manifest (it quotes the scope block and
    # the verdict counts), so its digest cannot be known until the manifest
    # exists. Built here, then listed in the same file table as everything
    # else -- the manifest covers every file in the archive but itself, and a
    # README left out of that table would be the one file nobody could check.
    readme = readme_text(manifest).encode("utf-8")
    manifest["files"] = files + [{"path": README_NAME, "bytes": len(readme),
                                  "sha256": _sha256(readme)}]

    entries = [(README_NAME, readme), (MANIFEST_NAME, manifest_json(manifest).encode("utf-8"))]
    entries += body

    out = Path(out)
    _write_zip(out, entries)
    _audit(out, manifest, sources)
    return manifest


def summary_line(manifest: dict, out: str | Path) -> str:
    c = manifest["verdict_counts"]
    n = c["receipts"]
    return (f"{n} receipt{'s' if n != 1 else ''}: {c[OK]} VERIFIED, {c[FAIL]} BROKEN, "
            f"{c[UNDETERMINED]} COULD NOT LOOK; {len(manifest['files']) + 1} files "
            f"in {Path(out).name}")
