"""Authorship Receipt: an edit stream recorded as it happened.

Buyer: a student accused by an AI detector, a writer certifying no-AI to a
publisher, a lawyer certifying under a no-AI-drafting order. The accusation
is a probability from a black box; the defense today is Google Docs version
history, which the accuser can say was staged. This receipt is the version
history with a spine: every edit event folded into a rolling hash as it
arrives, checkpointed into a hash chain, the final text bound at the end.

What it cannot do, printed on its face: it cannot prove a human produced
the keystrokes. A script can emit key events. What it can prove is that the
text came into being through the recorded sequence of typed and pasted
spans over the recorded span of time, and that no event was inserted,
removed or reordered after the fact. Typed-vs-pasted and the time profile
are what a reader weighs; the receipt supplies them and draws no verdict.

The name of the product is Daniel's call (his 9/5 idea, 'human-input
attestation'); the working name here is authorship.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Optional

from arcaeon.record.ledger import Ledger, digest_bytes

from .core import _now_iso, build_receipt, render_exhibit

KIND = "authorship-process"
CHECKPOINT_EVERY = 500
OPS = ("type", "paste", "delete", "idle")

SCOPE = {
    "proves": [
        "The recorded edit events (typed spans, pasted spans, deletions, idle gaps) were folded into a "
        "rolling hash in the order and at the times recorded, and checkpointed into the issuer's hash "
        "chain as the session ran; no event was inserted, removed or reordered afterward.",
        "The final text's digest was bound at session end, and the counts of typed and pasted "
        "characters are computed from the same recorded events.",
    ],
    "does_not_prove": [
        "That a human produced the events: software can emit key events. This is process evidence, "
        "not a humanity test, and it makes no claim about the author beyond the asserted name.",
        "That pasted text was written by the author, or was not generated by a model.",
        "Anything about text edited outside the recording session.",
    ],
    "method": "rolling sha256 over canonical event JSON, ledger checkpoints every "
              f"{CHECKPOINT_EVERY} events and at close; final text bound by sha256.",
}


def _fold(prev: str, event: dict) -> str:
    return hashlib.sha256((prev + json.dumps(event, sort_keys=True, separators=(",", ":"))).encode()).hexdigest()


class AuthorshipSession:
    def __init__(self, ledger_path: str | Path, *, namespace: str = "authorship",
                 author: str = "", document: str = ""):
        self.ledger_path = Path(ledger_path)
        self.ledger = Ledger(self.ledger_path)
        self.namespace, self.author, self.document = namespace, author, document
        self.session_id = hashlib.sha256(f"{_now_iso()}|{author}|{document}".encode()).hexdigest()[:16]
        self.started_at = _now_iso()
        self.rolling = "genesis"
        self.events = 0
        self.typed = self.pasted = self.deleted = 0
        self.paste_events = 0
        self.checkpoints: list = []
        self.first_ts: Optional[str] = None
        self.last_ts: Optional[str] = None
        self.ledger.append({"evt": "authorship_open", "namespace": namespace,
                            "session": self.session_id, "author": author, "document": document})

    def event(self, op: str, n: int = 0, *, ts: Optional[str] = None, text: Optional[str] = None,
              span_digest: Optional[str] = None) -> str:
        """Record one edit event. `text` (the span) is digested, never stored:
        the receipt must be shareable with an accuser without handing them a
        keylog. A recorder that already digested the span (the browser page)
        passes `span_digest` instead of text, so an ingested export folds to
        the same rolling hash the recorder showed. Returns the new rolling hash."""
        if op not in OPS:
            raise ValueError(f"op must be one of {OPS}")
        ts = ts or _now_iso()
        ev = {"seq": self.events + 1, "op": op, "n": int(n), "ts": ts}
        if text is not None:
            ev["span_digest"] = digest_bytes(text.encode("utf-8"))
            if not n:
                ev["n"] = len(text)
        elif span_digest:
            ev["span_digest"] = span_digest
        self.rolling = _fold(self.rolling, ev)
        self.events += 1
        self.first_ts = self.first_ts or ts
        self.last_ts = ts
        if op == "type":
            self.typed += ev["n"]
        elif op == "paste":
            self.pasted += ev["n"]
            self.paste_events += 1
        elif op == "delete":
            self.deleted += ev["n"]
        if self.events % CHECKPOINT_EVERY == 0:
            self._checkpoint("periodic")
        return self.rolling

    def _checkpoint(self, why: str) -> str:
        chain = self.ledger.append({"evt": "authorship_checkpoint", "namespace": self.namespace,
                                    "session": self.session_id, "events": self.events,
                                    "rolling": self.rolling, "why": why})
        self.checkpoints.append({"events": self.events, "rolling": self.rolling, "chain": chain, "at": _now_iso()})
        return chain

    def close(self, final_text: str, *, witness: bool = True, anchor: bool = True,
              extra: Optional[dict] = None) -> dict:
        self._checkpoint("close")
        total_in = self.typed + self.pasted
        check = {"session": self.session_id, "events": self.events,
                 "first_event": self.first_ts, "last_event": self.last_ts,
                 "typed_chars": self.typed, "pasted_chars": self.pasted,
                 "paste_events": self.paste_events, "deleted_chars": self.deleted,
                 "pasted_share": round(self.pasted / total_in, 3) if total_in else None,
                 "final_text_sha256": digest_bytes(final_text.encode("utf-8")),
                 "final_text_chars": len(final_text),
                 "rolling_hash": self.rolling, "checkpoints": self.checkpoints}
        subject = {"author": self.author or "(asserted name absent)", "document": self.document or "(untitled)",
                   "session": self.session_id, "started_at": self.started_at}
        return build_receipt(KIND, subject, [check], SCOPE, ledger_path=self.ledger_path,
                             namespace=self.namespace, witness=witness, anchor=anchor, extra=extra)


def replay(events: list, *, start: str = "genesis") -> str:
    """Recompute the rolling hash from a saved event list (the author keeps
    the events; the receipt keeps only the hash). A stranger with both can
    confirm the receipt's rolling_hash without the issuer."""
    h = start
    for ev in events:
        h = _fold(h, ev)
    return h


def _line(c: dict) -> str:
    share = c.get("pasted_share")
    share_s = f"{share:.0%}" if isinstance(share, float) else "n/a"
    return (f"{c.get('events')} events {c.get('first_event')} -> {c.get('last_event')}; "
            f"typed {c.get('typed_chars')} / pasted {c.get('pasted_chars')} in {c.get('paste_events')} paste(s) "
            f"({share_s} pasted); final text {c.get('final_text_chars')} chars {str(c.get('final_text_sha256'))[-16:]}")


def exhibit(receipt: dict) -> str:
    return render_exhibit(receipt, title="AUTHORSHIP PROCESS RECEIPT", check_line=_line)
