"""Parity tests for web/verify-receipt.html's embedded json-c14n v1
canonicalizer, against the vectors generated by tools/c14n_vectors.py.

Two independent legs, both always meaningful:

  1. Python leg (always runs): confirms arcaeon_ledger.digest_json reproduces
     every vector's expected canonical string and sha256 hex -- i.e. that the
     vectors themselves are trustworthy ground truth, not just self-consistent
     with the tool that generated them.

  2. JS leg (runs only if `node` is on PATH, else skipped with a clear
     reason): extracts the page's own canonicalizer -- the code between the
     `// C14N-START` and `// C14N-END` markers in web/verify-receipt.html --
     and evaluates it in a Node subprocess, then feeds it every vector's raw
     JSON text and compares the result to the expected canonical string. This
     is the actual code shipped in the page, not a reimplementation of it.

NOTE (K-011, 2026-09-12): checked on contact and corrected here rather than
re-derived blind. `web/verify-receipt.html` carries NO per-kind "supported
kind" list of any sort -- it renders any receipt generically off the 7
BODY_FIELDS (buildBodyNode() in the page's JS), so a `ballot` receipt needs
zero page changes to render or verify; there was nothing to "add ballot to".
And this file, before this pass, had no per-adapter round-trip tests
"alongside cite/call/approval/authorship" -- only the generic canonicalization
vectors above. `test_full_ballot_receipt_body_digest_matches_js_canonicalizer`
below is the first concrete per-receipt-kind round trip in this file, using a
real, built `ballot` receipt as the worked example, since none existed to
extend.
"""
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

from arcaeon.record.ledger import digest_json

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from c14n_vectors import generate_vectors  # noqa: E402

HTML_PATH = ROOT / "web" / "verify-receipt.html"
START_MARK = "// C14N-START"
END_MARK = "// C14N-END"

VECTORS = generate_vectors()


def _extract_js_canonicalizer() -> str:
    text = HTML_PATH.read_text(encoding="utf-8")
    start = text.index(START_MARK)
    end = text.index(END_MARK)
    assert start < end, "C14N-START must appear before C14N-END in web/verify-receipt.html"
    return text[start:end]


def test_html_file_exists_and_has_markers():
    assert HTML_PATH.exists(), "web/verify-receipt.html is missing"
    text = HTML_PATH.read_text(encoding="utf-8")
    assert text.count(START_MARK) == 1, "expected exactly one C14N-START marker"
    assert text.count(END_MARK) == 1, "expected exactly one C14N-END marker"


@pytest.mark.parametrize("vector", VECTORS, ids=lambda v: v.name)
def test_python_side_matches_arcaeon_ledger_digest_json(vector):
    """The vectors are ground truth only if arcaeon_ledger agrees with them --
    this checks the actual library the receipts are verified against, not
    just tools/c14n_vectors.py's own copy of the recipe."""
    value = json.loads(vector.input_text)
    expected_full_digest = f"sha256:json-c14n:v1:{vector.expected_sha256_hex}"
    assert digest_json(value) == expected_full_digest, (
        f"{vector.name}: arcaeon_ledger.digest_json disagrees with the vector"
    )


def test_js_canonicalizer_parity_via_node():
    node = shutil.which("node")
    if node is None:
        pytest.skip(
            "node is not on PATH; cannot run the JS parity check for "
            "web/verify-receipt.html's canonicalizer. The Python-side test "
            "above still confirms the vectors are correct; this leg only "
            "confirms the page's JS reproduces them, and needs Node to do so."
        )

    js_module = _extract_js_canonicalizer()
    # Vectors go in and results come out through FILES, explicitly read/written
    # as UTF-8, never through argv or a captured stdout pipe: on Windows those
    # get transcoded through the console/ANSI code page, which mangles the
    # non-ASCII vectors (café / 中文 / the emoji) into mojibake before Node or
    # Python ever sees the real bytes. Files sidestep that entirely.
    with tempfile.TemporaryDirectory() as td:
        vectors_path = Path(td) / "vectors.json"
        results_path = Path(td) / "results.json"
        script_path = Path(td) / "harness.js"

        vectors_path.write_text(
            json.dumps([v.as_dict() for v in VECTORS], ensure_ascii=False), encoding="utf-8"
        )
        harness = js_module + "\n" + r"""
const fs = require('fs');
const vectorsPath = process.argv[2];
const resultsPath = process.argv[3];
const vectors = JSON.parse(fs.readFileSync(vectorsPath, 'utf8'));
const results = vectors.map(function (v) {
  try {
    return { name: v.name, ok: true, canonical: c14nCanonicalize(v.input_text) };
  } catch (e) {
    return { name: v.name, ok: false, error: String((e && e.message) || e) };
  }
});
fs.writeFileSync(resultsPath, JSON.stringify(results), 'utf8');
"""
        script_path.write_text(harness, encoding="utf-8")

        proc = subprocess.run(
            [node, str(script_path), str(vectors_path), str(results_path)],
            capture_output=True, encoding="utf-8", timeout=30,
        )
        assert proc.returncode == 0, f"node harness failed (stderr):\n{proc.stderr}"

        try:
            results = {r["name"]: r for r in json.loads(results_path.read_text(encoding="utf-8"))}
        except json.JSONDecodeError:
            pytest.fail(f"node harness produced non-JSON results file, stderr:\n{proc.stderr}")

    failures = []
    for v in VECTORS:
        r = results.get(v.name)
        if r is None:
            failures.append(f"{v.name}: no result returned from node")
        elif not r["ok"]:
            failures.append(f"{v.name}: JS canonicalizer threw: {r['error']}")
        elif r["canonical"] != v.expected_canonical:
            failures.append(
                f"{v.name}: JS produced {r['canonical']!r}, expected {v.expected_canonical!r}"
            )
    assert not failures, "canonicalization mismatches:\n" + "\n".join(failures)


def test_full_ballot_receipt_body_digest_matches_js_canonicalizer(tmp_path):
    """A real, built `ballot` receipt (not a synthetic vector): its 7-field
    body, fed through the page's own JS canonicalizer, must reproduce exactly
    the body_digest core.py computed for it. This is the round trip K-011
    actually needed -- verify-receipt.html has no per-kind logic to update,
    so the meaningful check is that a full ballot receipt's real body
    survives the page's canonicalizer unchanged, the same as any other kind."""
    node = shutil.which("node")
    if node is None:
        pytest.skip("node is not on PATH; cannot run the JS parity check")

    from arcaeon.record.receipt import ballot

    rc = ballot.ballot_receipt(
        {"overall": {"score": 82, "verdict": "GOOD", "summary": "Passes."},
         "per_answer": [{"score": 82.0, "verdict": "GOOD"}]},
        trainee="a. writer", scenario="oral_board.set1", grader="ascenvo.vcs.oral_board",
        timestamp="2026-09-12T08:00:00Z", ledger_path=tmp_path / "l.jsonl",
        witness=False, anchor=False,
    )
    body = {k: rc.get(k) for k in
            ["receipt_version", "kind", "issued_at", "subject", "checks", "scope", "extra"]}
    body_json = json.dumps(body, ensure_ascii=False)

    js_module = _extract_js_canonicalizer()
    with tempfile.TemporaryDirectory() as td:
        body_path = Path(td) / "body.json"
        result_path = Path(td) / "result.json"
        script_path = Path(td) / "harness.js"
        body_path.write_text(body_json, encoding="utf-8")
        harness = js_module + "\n" + r"""
const fs = require('fs');
const bodyText = fs.readFileSync(process.argv[2], 'utf8');
let out;
try {
  out = { ok: true, canonical: c14nCanonicalize(bodyText) };
} catch (e) {
  out = { ok: false, error: String((e && e.message) || e) };
}
fs.writeFileSync(process.argv[3], JSON.stringify(out), 'utf8');
"""
        script_path.write_text(harness, encoding="utf-8")
        proc = subprocess.run([node, str(script_path), str(body_path), str(result_path)],
                              capture_output=True, encoding="utf-8", timeout=30)
        assert proc.returncode == 0, f"node harness failed (stderr):\n{proc.stderr}"
        result = json.loads(result_path.read_text(encoding="utf-8"))

    assert result["ok"], result.get("error")
    import hashlib
    expected_digest = "sha256:json-c14n:v1:" + hashlib.sha256(
        result["canonical"].encode("utf-8")).hexdigest()
    assert expected_digest == rc["body_digest"], (
        "the JS canonicalizer's output does not hash to the same body_digest core.py issued "
        "for this ballot receipt"
    )


def test_branded_ballot_receipt_verifies_on_the_page_with_no_verifier_change(tmp_path):
    """Task 087's requirement 4, proven rather than asserted: a VENDOR-BRANDED
    ballot receipt -- issuer and cohort sealed in the body's `extra` dict --
    round-trips through web/verify-receipt.html's own canonicalizer to the
    exact body_digest core.py issued.

    `extra` was already one of the 7 BODY_FIELDS the page canonicalizes, and
    the page has no per-kind logic at all (see this file's module note), so
    branding needed ZERO edit to the verifier. This test is what makes that
    a checked fact instead of a reading of the code: if a future change put
    branding anywhere the page does not canonicalize, this fails."""
    node = shutil.which("node")
    if node is None:
        pytest.skip("node is not on PATH; cannot run the JS parity check")

    from arcaeon.record.receipt import ballot

    rc = ballot.ballot_receipt(
        {"overall": {"score": 82, "verdict": "GOOD", "summary": "Passes."}},
        trainee="p. lindqvist", scenario="oral_board.set1", grader="ascenvo.vcs.oral_board",
        timestamp="2026-09-13T17:41:02Z", ledger_path=tmp_path / "l.jsonl",
        namespace="wrta-ob-14", witness=False, anchor=False,
        issuer="Westbrook Regional Training Academy", cohort="WRTA-2026-OB-14",
    )
    assert rc["extra"] == {"issuer": "Westbrook Regional Training Academy",
                           "cohort": "WRTA-2026-OB-14"}
    body = {k: rc.get(k) for k in
            ["receipt_version", "kind", "issued_at", "subject", "checks", "scope", "extra"]}

    js_module = _extract_js_canonicalizer()
    with tempfile.TemporaryDirectory() as td:
        body_path = Path(td) / "body.json"
        result_path = Path(td) / "result.json"
        script_path = Path(td) / "harness.js"
        body_path.write_text(json.dumps(body, ensure_ascii=False), encoding="utf-8")
        harness = js_module + "\n" + r"""
const fs = require('fs');
const bodyText = fs.readFileSync(process.argv[2], 'utf8');
let out;
try {
  out = { ok: true, canonical: c14nCanonicalize(bodyText) };
} catch (e) {
  out = { ok: false, error: String((e && e.message) || e) };
}
fs.writeFileSync(process.argv[3], JSON.stringify(out), 'utf8');
"""
        script_path.write_text(harness, encoding="utf-8")
        proc = subprocess.run([node, str(script_path), str(body_path), str(result_path)],
                              capture_output=True, encoding="utf-8", timeout=30)
        assert proc.returncode == 0, f"node harness failed (stderr):\n{proc.stderr}"
        result = json.loads(result_path.read_text(encoding="utf-8"))

    assert result["ok"], result.get("error")
    import hashlib
    assert "Westbrook Regional Training Academy" in result["canonical"], (
        "the issuer is not present in the canonical string the page hashes -- "
        "branding would then be outside the seal"
    )
    expected_digest = "sha256:json-c14n:v1:" + hashlib.sha256(
        result["canonical"].encode("utf-8")).hexdigest()
    assert expected_digest == rc["body_digest"]
