"""Write web/universal/c14n_pinned.js and web/universal/crosscheck_pinned.js
from web/verify-receipt.html.

Two blocks of verify-receipt.html have ONE source, that page:
  * `// C14N-START` .. `// C14N-END`: the json-c14n v1 canonicalizer, pinned by
    tests/test_verify_page_parity.py;
  * `// CROSSCHECK-START` .. `// CROSSCHECK-END`: the checks of the witness
    block and the attestation signature against the receipt they are attached
    to (added 2026-09-22 so verify-any.html cannot say VERIFIED where
    verify-receipt.html says FAIL).
web/verify-any.html needs the same code, and verify-receipt.html has to stay a
single self-contained file (the site copy is held byte-identical to it and may
not load any <script src>), so each block is copied out here, never edited
here, and tests/test_universal_checker.py fails if either ever differs.

Run: py tools/extract_c14n.py         (writes both files)
     py tools/extract_c14n.py --check (exit 1 if either file is stale)
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "verify-receipt.html"
DST = ROOT / "web" / "universal" / "c14n_pinned.js"
START, END = "// C14N-START", "// C14N-END"
HEADER = (
    "/* GENERATED by tools/extract_c14n.py from web/verify-receipt.html.\n"
    " * Do not edit: this is the pinned json-c14n v1 block, byte for byte.\n"
    " * tests/test_universal_checker.py fails if it drifts from the source. */\n"
    '"use strict";\n'
)
XDST = ROOT / "web" / "universal" / "crosscheck_pinned.js"
XSTART, XEND = "// CROSSCHECK-START", "// CROSSCHECK-END"
XHEADER = (
    "/* GENERATED by tools/extract_c14n.py from web/verify-receipt.html.\n"
    " * Do not edit: this is the pinned cross-check block (the witness block and\n"
    " * the attestation signature against the receipt), byte for byte.\n"
    " * tests/test_universal_checker.py fails if it drifts from the source. */\n"
    '"use strict";\n'
)


def block(text: str, start: str = START, end: str = END) -> str:
    text = text.replace("\r\n", "\n")
    assert text.count(start) == 1 and text.count(end) == 1, "expected exactly one " + start + " and one " + end
    s, e = text.index(start), text.index(end)
    assert s < e
    return text[s:e + len(end)] + "\n"


def expected() -> str:
    return HEADER + block(SRC.read_text(encoding="utf-8"))


def expected_crosscheck() -> str:
    return XHEADER + block(SRC.read_text(encoding="utf-8"), XSTART, XEND)


TARGETS = ((DST, expected), (XDST, expected_crosscheck))


def main() -> int:
    if "--check" in sys.argv:
        stale = 0
        for dst, make in TARGETS:
            have = dst.read_text(encoding="utf-8").replace("\r\n", "\n") if dst.exists() else ""
            if have != make():
                print("stale: " + dst.relative_to(ROOT).as_posix() + " differs from its verify-receipt.html block")
                stale = 1
        if not stale:
            print("ok")
        return stale
    for dst, make in TARGETS:
        dst.write_bytes(make().encode("utf-8"))
        print("wrote", dst)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
